# Generated by Django 5.0.3 on 2024-03-25 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_description_todo_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todos.todo')),
            ],
            bases=('todos.todo', models.Model),
        ),
    ]
