# Generated by Django 5.0.3 on 2024-03-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashbin',
            name='title',
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.DeleteModel(
            name='TrashBin',
        ),
    ]
