# Generated by Django 5.0.3 on 2024-03-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='lable',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
