# Generated by Django 5.0.3 on 2024-03-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_todo_lable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='lable',
            new_name='label',
        ),
    ]
