# Generated by Django 5.0.3 on 2024-03-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_rename_lable_todo_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
    ]
