# Generated by Django 5.0.3 on 2024-04-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_archive_todo_is_archived_alter_todo_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='label',
            field=models.CharField(max_length=128),
        ),
    ]
