# Generated by Django 5.0.3 on 2024-04-11 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_delete_archive_rename_username_todo_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='label',
            field=models.ForeignKey(default=None, max_length=128, on_delete=django.db.models.deletion.PROTECT, to='todos.label'),
        ),
    ]
