# Generated by Django 5.0.3 on 2024-04-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0013_remove_todo_label_todo_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, to='todos.label'),
        ),
    ]
