# Generated by Django 5.0.3 on 2024-05-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0014_alter_todo_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='labels',
        ),
        migrations.AddField(
            model_name='todo',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='todos.label'),
        ),
    ]
