# Generated by Django 5.0.3 on 2024-05-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0015_remove_todo_is_archived_remove_todo_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default=False, max_length=6),
        ),
    ]
