# Generated by Django 5.0.3 on 2024-05-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0017_alter_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_pined',
            new_name='is_pinned',
        ),
    ]
