# Generated by Django 5.0.3 on 2024-12-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0019_todo_time_trashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='label',
            field=models.CharField(default='No label', max_length=128),
        ),
    ]
